---
title: "Lista 4"
author:
- 'Aluno: Gustavo Luiz Bispo dos Santos - 117210400'
- 'Aluno: Diego Amancio Pereira - 116210716'
- 'Aluno: Gilmar Gonzaga da Silva - 119211123'
date: 'Data: 05/06/2022'
output:
  pdf_document: default
  html_document: default
---

```{r, include=FALSE}
library(Rlab)
```

### Questão 1
_Uma v.a. X tem distribuição normal, com média 100 e desvio padrão 10._

_a) Qual a P(90 < X < 110)?_

**Resposta** 0,68268 ou 68,27%

_b) Se X for a média de uma amostra de 16 elementos retiradas dessa população, calcule P(90 < X < 110)._

**Resposta** 0,9999 ou 99,99%

_c) Usando a linguagem R, represente, num único gráfico, as distribuições de X e X._

**Resposta**

_d) Que tamanho deveria ter a amostra para que P(90 < X < 110) = 0, 95?_

**Resposta** 4

### Questão 2
_A máquina de empacotar um determinado produto o faz segundo uma distribuição normal,com média µ e desvio padrão 10 g_

_a) Em quanto deve ser regulado o peso médio µ para que apenas 10% dos pacotes tenham menos do que 500 g?_

**Resposta** 512,8

_b) Com a máquina assim regulada, qual a probabilidade de que o peso total de 4 pacotes escolhidos ao acaso seja inferior a 2 kg?_

**Resposta** aproximadamente 0,5%

### Questão 3
_No exemplo anterior, e após a máquina estar regulada, programou-se uma carta de controle de qualidade. De hora em hora, será retirada uma amostra de quatro pacotes e esses serão pesados. Se a média da amostra for inferior a 495 g ou superior a 520 g, encerra-se a produção para reajustar a máquina, isto é, reajustar o peso médio._

_a) Qual a probabilidade de ser feita uma parada desnecessária?_

**Resposta** 7,57%

_b) Se o peso médio da máquina desregulou-se para 500 g, qual a probabilidade de continuar a produção fora dos padrões desejados?_

**Resposta**  72,57%

### Questão 4
_Um procedimento de controle de qualidade foi planejado para garantir um máximo de 10% de itens defeituosos na produção. A cada 6 horas sorteia-se uma amostra de 20 peças e, havendo mais de 15% de defeituosos, encerra-se a produção para verificação do processo. Qual a probabilidade de uma parada desnecessária?_

**Resposta**  aproximadamente 22,9%

### Questão 5
_Suponha que a produção do exemplo anterior esteja sob controle, isto é, p = 10%, e que os itens sejam vendidos em caixas com 100 unidades. Usando a distribuição de probabilidade exata e aproximada da variável Sn: total de itens defeituosos em uma caixa, calcule manualmente e ou usando o R a probabilidade de que uma caixa:_

_a) tenha mais do que 10% de itens defeituosos? _

**Resposta** A probabilidade de uma proporção de mais de 0.1 defeituosos é dada por P(Z > 0) = 0.5

_b) não tenha itens defeituosos?_

**Resposta** P(0 defeituosos em 100) = 0.9^100 ~= 2.65 × 10^-5, ou quase zero.

### Questão 6
**Voluntários se quotizam para realizar uma obra**
_Uma instituição de caridade deseja realizar uma obra que custa R$3500,00 em sua sede. Entre os contribuintes habituais dessa instituição, cada um pode contribuir com algo em torno de R$120,00 um desvio padrão de R$50,00. Se 30 dessas pessoas se quotizarem para levantar fundos com essa finalidade, qual a probabilidade de que eles consigam o montante necessário?_

**Resposta** A chance da obra ser realizada com base nesses 30 donativos seria de aproximadamente 64%.


### Questão 7
**Pesquisa de mercado**
_Uma empresa estuda a possibilidade de lançar no mercado um novo detergente, por um preço um pouco mais alto do que o dos produtos similares, mas supostamente de qualidade muito superior. Para isso ela encomendou uma pesquisa de mercado onde $200$ consumidores escolhidos aleatoriamente serão ouvidos sobre sua intenção de adquirir o novo produto. A empresa sóo pretende lançá-lo de fato no mercado se pelo menos $40$ entre os consumidores consultados responderem favoravelmente. Seja $p$ a verdadeira proporção populacional dos consumidores dispostos a usar o novo produto._

Trabalhando com a variável $S_{200}$: total de consumidores favoráveis à aquisição do novo detergente dentre os $200$ e, se $p = 0,15$:

i) Calcule a probabilidade de que o lançamento ocorrerá utilizando a distribuição exata da variável $S_{200}$.

**Resposta** $P(X \leq 40) ~= 0.9812$

ii) Verifique se as condições de aproximação da distribuição binomial pela normal indicam uma boa aproximação da binomial para a distribuição normal.

**Resposta** tendo em vista o resultado obtido na questão anterior, sim.

iii) Calcule a probabilidade de que o lançamento ocorrerá utilizando a distribuição aproximada da variável $S_{200}$ sem e com a correção de continuidade.

**Resposta** 

Com correção: 

$Pr(pˆ \leq 40)= Pr(Z\leq 1578.39)$

$Pr(pˆ \leq 40)=1.$

Sem correção:

$Pr(pˆ \leq 40)= Pr(Z\leq 1578.3)$

$Pr(pˆ \leq 40)=1.$

iv) Calcule a probabilidade de que o lançamento ocorrerá utilizando a distribuição da proporção amostral, $P$.

v) Comente sobre os resultados obtidos nos itens acima.

**Resposta** Tendo em vista os resultados obtidos nas resoluções acima, fica evidente que a propabilidade do produto ser lançado no mercado é muito grande, pois, na maioria das vezes, temos uma probabilidade próxima a 100%.









